name: Notification Robot

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  notification:
    runs-on: ubuntu-latest
    env:
      APP_TOKEN: ${{ secrets.APP_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Notify
        run: curl "https://notify.yutu0k.top/message?token=$APP_TOKEN" -F "title=吃药啦吃药啦" -F "message=popo提醒猫咪该吃药噜" -F "priority=5"
