name: Notification Robot

on:
  schedule:
    - cron: '0-59/3 * * * *'
  workflow_dispatch:

jobs:
  notification:
    runs-on: ubuntu-latest
    env:
      APP_TOKEN: ${{ secrets.APP_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Notify
        run: curl "https://notify.yutu0k.top/message?token=$APP_TOKEN" -F "title=test title" -F "message=test message" -F "priority=5"
